### ISSUE TITLE
Using synchronize_expectation globally

### ISSUE THREAD

**Issue by simonasdev** [ElMassimo/capybara_test_helpers#5]
Hi. 
Just started using your gem but can't really get how can I use `synchronize_expectation` globally in my tests. 
After defining base test helper like so:
```ruby
class BaseTestHelper < Capybara::TestHelper
end
```
and verifying that this class indeed defines `synchronize_expectation` method I've tried using it in my globally included module like so:
```ruby
module GlobalTestHelper
  extend ActiveSupport::Concern

  included do
    use_test_helpers(:base)
  end
end
```
But when calling `synchronize_expectation` I'm still getting `undefined method synchronize_expectation for #<RSpec::ExampleGroups::Dashboard::NewUser:0x00007f99afaa5cd0>`. 
Even if I delegate the method to base with `delegate :synchronize_expectation, to: :base` inside of `included` block, I'm still getting `protected method synchronize_expectation called for #<BaseTestHelper 70144865172940>`. So it seems to me that `synchronize_expectation` can only be called without explicit receiver, hence only inside of subclasses of `Capybara::TestHelper`.
Any ideas what I'm missing? The example does not include this use case as far as I've noticed

**Comment by simonasdev** [comment]
For now I've settled by implementing `synchronize_expectation` in `BaseTestHelper`:
```ruby
class BaseTestHelper < Capybara::TestHelper
  def synchronize_expectation(*args)
    super
  end
end
```
but this seems really unnecessary

**Comment by ElMassimo** [comment]
By default, `synchronize_expectation` is `protected`, because it's meant to be used inside test helpers, where it can be properly encapsulated.

Using it directly in tests can make them significantly harder to read.

If you really need to, you can change the method visibility to `public` instead:

```ruby
class BaseTestHelper < Capybara::TestHelper
  public :synchronize_expectation
end
```
